version: '3'

services:
  nextjs:
    build: .
    container_name: nextjs
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - chatservice-network

  db:
    image: mysql:8.0.30-debian
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chat
    volumes:
      - .docker/dbdata:/var/lib/mysql
    networks:
      - chatservice-network

  keycloak:
    image: quay.io/keycloak/keycloak:21.0
    command: start-dev
    ports:
      - 9000:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

networks:
  chatservice-network:
    external: true
